name: pubsub
description: Lightweight Publish/Subscribe library.
version: 1.0.0
homepage: https://github.com/nayarsystems/pubsub-dart
author: jaracil <pepe.aracil.gomez@gmail.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
