name: ps
description: Lightweight Publish / Subscribe library. Supports sticky messages and streams.
version: 1.0.11
homepage: https://github.com/nayarsystems/pubsub-dart
author: jaracil <pepe.aracil.gomez@gmail.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  meta: ^1.1.6

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
